### ISSUE TITLE
Connected No Internet

### ISSUE THREAD

**Issue by cheshmghermezi** [davidemyers/algo-pfsense#1]
Hi there,
First thanks for your step by step tutorial which I was able to follow exactly.
![Screenshot_5](https://user-images.githubusercontent.com/58072817/69514324-23325680-0f60-11ea-9345-c8cea9debed2.png)
![Screenshot_6](https://user-images.githubusercontent.com/58072817/69514326-23325680-0f60-11ea-8a20-a9d3cc0fa736.png)
However when it gets connected I lost my internet access no ping no anything. (I changed the dns resolver settings you mentioned also) And have to change it to disable to gain access back. I have openvpn and some rules in my pf. is ipsec conflicting openvpn?

**Comment by cheshmghermezi** [comment]
Last 50 IPsec Log Entries. (Maximum 50)
Nov 25 08:36:55	charon		08[CFG] vici client 27 connected
Nov 25 08:36:55	charon		09[CFG] vici client 27 registered for: list-sa
Nov 25 08:36:55	charon		08[CFG] vici client 27 requests: list-sas
Nov 25 08:36:55	charon		10[CFG] vici client 27 disconnected
Nov 25 08:37:01	charon		09[CFG] vici client 28 connected
Nov 25 08:37:01	charon		11[CFG] vici client 28 registered for: list-sa
Nov 25 08:37:01	charon		09[CFG] vici client 28 requests: list-sas
Nov 25 08:37:01	charon		09[CFG] vici client 28 disconnected
Nov 25 08:37:07	charon		10[CFG] vici client 29 connected
Nov 25 08:37:07	charon		15[CFG] vici client 29 registered for: list-sa
Nov 25 08:37:07	charon		10[CFG] vici client 29 requests: list-sas
Nov 25 08:37:07	charon		15[CFG] vici client 29 disconnected
Nov 25 08:37:13	charon		10[CFG] vici client 30 connected
Nov 25 08:37:13	charon		11[CFG] vici client 30 registered for: list-sa
Nov 25 08:37:13	charon		15[CFG] vici client 30 requests: list-sas
Nov 25 08:37:13	charon		11[CFG] vici client 30 disconnected
Nov 25 08:37:19	charon		15[CFG] vici client 31 connected
Nov 25 08:37:19	charon		01[CFG] vici client 31 registered for: list-sa
Nov 25 08:37:19	charon		01[CFG] vici client 31 requests: list-sas
Nov 25 08:37:19	charon		01[CFG] vici client 31 disconnected
Nov 25 08:37:25	charon		11[CFG] vici client 32 connected
Nov 25 08:37:25	charon		12[CFG] vici client 32 registered for: list-sa
Nov 25 08:37:25	charon		11[CFG] vici client 32 requests: list-sas
Nov 25 08:37:25	charon		11[CFG] vici client 32 disconnected
Nov 25 08:37:30	charon		01[CFG] vici client 33 connected
Nov 25 08:37:30	charon		06[CFG] vici client 33 registered for: list-sa
Nov 25 08:37:30	charon		06[CFG] vici client 33 requests: list-sas
Nov 25 08:37:30	charon		06[CFG] vici client 33 disconnected
Nov 25 08:39:07	charon		15[CFG] vici client 34 connected
Nov 25 08:39:07	charon		12[CFG] vici client 34 registered for: list-sa
Nov 25 08:39:07	charon		12[CFG] vici client 34 requests: list-sas
Nov 25 08:39:07	charon		12[CFG] vici client 34 disconnected
Nov 25 08:39:10	charon		12[IKE] <con1000|1> sending DPD request
Nov 25 08:39:10	charon		12[IKE] <con1000|1> queueing IKE_DPD task
Nov 25 08:39:10	charon		12[IKE] <con1000|1> activating new tasks
Nov 25 08:39:10	charon		12[IKE] <con1000|1> activating IKE_DPD task
Nov 25 08:39:10	charon		12[ENC] <con1000|1> generating INFORMATIONAL request 30 [ ]
Nov 25 08:39:10	charon		12[NET] <con1000|1> sending packet: from xx.my.ip.xx[500] to 74.118.139.6[500] (57 bytes)
Nov 25 08:39:10	charon		12[NET] <con1000|1> received packet: from 74.118.139.6[500] to xx.my.ip.xx[500] (57 bytes)
Nov 25 08:39:10	charon		12[ENC] <con1000|1> parsed INFORMATIONAL response 30 [ ]
Nov 25 08:39:10	charon		12[IKE] <con1000|1> activating new tasks
Nov 25 08:39:10	charon		12[IKE] <con1000|1> nothing to initiate
Nov 25 08:39:12	charon		15[CFG] vici client 35 connected
Nov 25 08:39:12	charon		10[CFG] vici client 35 registered for: list-sa
Nov 25 08:39:12	charon		15[CFG] vici client 35 requests: list-sas
Nov 25 08:39:12	charon		15[CFG] vici client 35 disconnected
Nov 25 08:39:17	charon		10[CFG] vici client 36 connected
Nov 25 08:39:17	charon		06[CFG] vici client 36 registered for: list-sa
Nov 25 08:39:17	charon		15[CFG] vici client 36 requests: list-sas
Nov 25 08:39:17	charon		15[CFG] vici client 36 disconnected

**Comment by davidemyers** [comment]
I've never used OpenVPN.

Make sure the `updown` script ran correctly on your Algo server. Run `sudo iptables-save` and look for rules containing your pfSense LAN IP address.
