### ISSUE TITLE
How to configure IPsec with ikev2? 

### ISSUE THREAD

**Issue by PedroPCardoso** [davidemyers/algo-pfsense#3]
I created a ubuntu 18.04 server, now I need to use ipsec for an Cisco RV340 router.

But there are some fields that I don't know which options to use.

I tried to use the project https://github.com/davidemyers/algo-pfsense, but without success, I did not find in the documentation anything that would explain the steps to solve this type of problem.

Note: I created a .pem
![image_2020_03_19T14_27_47_786Z](https://user-images.githubusercontent.com/7657883/77356505-3219f180-6d25-11ea-80e7-e0a2fbcfbd2e.png)
![image_2020_03_19T14_30_18_671Z](https://user-images.githubusercontent.com/7657883/77356508-32b28800-6d25-11ea-9e8e-2a797bbb5099.png)
![image_2020_03_19T14_30_45_471Z](https://user-images.githubusercontent.com/7657883/77356509-334b1e80-6d25-11ea-9c38-05502377efe2.png)
![image_2020_03_19T14_33_43_792Z](https://user-images.githubusercontent.com/7657883/77356510-33e3b500-6d25-11ea-9330-b32dcde08975.png)

**Comment by davidemyers** [comment]
I don't see how this relates to pfSense so I'm closing it.
